### ISSUE TITLE
Syllabus: Use random numeric IDs or UUIDs for Mathigon sections

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/platypus#777] opened 2022-02-23 18:04 UTC
Currently the Mathigon sections defined in the file https://github.com/Qiskit/platypus/blob/main/notebooks/toc.yaml use slug-alike IDs.

To avoid making unintended changes to these IDs (for example when updating a title and wanting to keep the ID also consistent with the new update), we should use IDs that are less meaningful and probably more likely to be unique without needing to check (like a UUID or incrementing numbers).

If the IDs change, then the syllabi might point to non-existent IDs.

We also need to create tests to see if all referenced IDs exist.

**Comment by pandasa123** [comment] 2022-04-08 15:11
Is this a duplicate of #876?

**Comment by vabarbosa** [comment] 2024-02-08 04:44
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).

**Closed by vabarbosa** 2024-02-08 04:44 UTC
Labels: feature, ARCHIVED
