### ISSUE TITLE
Investigate why platypus is breaking from a clean installation

### ISSUE THREAD

**Issue by Tansito** [Qiskit/platypus#280] opened 2022-01-18 16:26 UTC
From a clean project doing a `npm install` generates errors in the front. We need to identify which dependency is creating the problem.

**Comment by techtolentino** [comment] 2022-01-18 21:10
@Tansito - I'm curious, what errors do you see on the front end? 

I _am_ seeing this error (missing CTA), but I'm not sure if this is what you're referring to.
<img width="1644" alt="Screen Shot 2022-01-18 at 1 09 34 PM" src="https://user-images.githubusercontent.com/6276074/150019420-8d24bc34-0de1-4dc1-b824-f40d1cb2f3cd.png">

**Comment by Tansito** [comment] 2022-01-19 10:05
Yeah, the error is `isExternal is not a function` that I think is generating the error in the test `1) next and previous links navigate to next and previous pages`. Only happens when you run `npm install` but not `npm ci`. We installed the renovate app to see if it was one of our dependencies but not, so a I got a bit stuck at this point.

**Comment by Tansito** [comment] 2022-01-19 11:05
Talking with @korgan00 it seems that we can try to do a workaround moving the static method from the class to an export method.

**Comment by vabarbosa** [comment] 2022-01-20 05:26
@Tansito @korgan00 i did some more investigation and the issue is with this `vue-loader-v16` which is  dependency of `@vue/cli-service`.

more specifically `@vue/cli-service` has a dependency of:

```json
"vue-loader-v16": "npm:vue-loader@^16.1.0"
```

currently, the `package-lock.json` includes the info for version `16.8.1`:

```json
        "vue-loader-v16": {
          "version": "npm:vue-loader@16.8.1",
          "resolved": "https://registry.npmjs.org/vue-loader/-/vue-loader-16.8.1.tgz",
          "integrity": "sha512-V53TJbHmzjBhCG5OYI2JWy/aYDspz4oVHKxS43Iy212GjGIG1T3EsB3+GWXFm/1z5VwjdjLmdZUFYM70y77vtQ==",
```

so when you run `npm ci` it installs that version and everything works as expected.

however, depending on the environment when you run `npm install` it installs `16.8.3`:

```json
        "vue-loader-v16": {
          "version": "npm:vue-loader@16.8.3",
          "resolved": "https://registry.npmjs.org/vue-loader/-/vue-loader-16.8.3.tgz",
          "integrity": "sha512-7vKN45IxsKxe5GcVCbc2qFU5aWzyiLrYJyUuMz4BQLKctCj/fmCa0w6fGiiQ2cLFetNcek1ppGJQDCup0c1hpA==",
```

and that causes some components to break.

i did not try to debug exactly what the issue with `16.8.3` is, but you can quickly checkout the difference between `16.8.1` and `16.8.3` here: https://github.com/vuejs/vue-loader/compare/v16.8.1...v16.8.3


in any case, one option to workaround this is by using the [`override` field in `package.json`](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides) to freeze the version of this nested dependency. however, this is only available/recognized in NPM v8.3 or greater.

since the problem is specifically with accessing static methods and effects just the `BasicLink` component, i think we could go with @korgan00's suggestion and move the static methods outside of the component class. i went ahead and submitted a PR for this approach: https://github.com/Qiskit/platypus/pull/301

**Comment by abdonrd** [comment] 2022-01-20 11:35
Another temporal solution it's add the `vue-loader-v16` pinned version to the `package.json`.
So it force keep this version.

https://github.com/Qiskit/platypus/pull/302

**Comment by Tansito** [comment] 2022-01-20 11:39
Personally between #301 and #302 I would prefer the first solution. It will enable us to update that library in case it requires a newer version of `vue-loader-v16`, what do you think?

**Comment by abdonrd** [comment] 2022-01-20 12:00
> Personally between #301 and #302 I would prefer the first solution. It will enable us to update `@vue/cli-service` in case it requires a newer version of `vue-loader-v16`, what do you think?

Agree! #302 is just a temporary workaround.

**Comment by abdonrd** [comment] 2022-01-21 10:02
Closed by https://github.com/Qiskit/platypus/pull/301

**Closed by abdonrd** 2022-01-21 10:02 UTC
Labels: bug
