### ISSUE TITLE
[Content UX] cannot highlight to copy/paste mathjax created material

### ISSUE THREAD

**Issue by JRussellHuffman** [Qiskit/platypus#443] opened 2021-10-07 15:18 UTC
### Steps to reproduce the problem
Go to any page with mathematical notation generated by mathjax and try to highlight that text, such as [this one](https://learn.qiskit.org/course/ch-algorithms/quantum-teleportation)

### What is the current behavior?
It cannot be highlighted. If there is standard text on either end of the mathjax material, that text is highlighted but the math is skipped.

### What is the expected behavior?
to be able to highlight and copy/paste mathematical notation.

**Comment by eddybrando** [comment] 2022-05-20 08:14
Duplicate of #428

**Closed by eddybrando** 2022-05-20 08:14 UTC
Labels: duplicate
