### ISSUE TITLE
[Analytics] Syllabus visits and creations not instrumented

### ISSUE THREAD

**Issue by pandasa123** [Qiskit/platypus#1010] opened 2022-05-16 19:59 UTC
### Steps to reproduce the problem

1. Go to https://learn.qiskit.org/syllabus/8HS-HDC
2. Check Segment extension
3. See that load isn't instrumented

OR 

1. Go to https://learn.qiskit.org/syllabus/create
2. Check Segment extension
3. See that creation isn't instrumented

### What is the current behavior?

The Syllabus page visits / loads, and the Syllabus creations are not instrumented. Only [redirects](https://analytics.amplitude.com/ibm/chart/new/55tfmdr) from learn are

### What is the expected behavior?

Segment should capture the following events on `/syllabus`:

- Page Load
- Syllabus Creation

**Comment by techtolentino** [comment] 2022-06-08 17:27
@pandasa123 - I have an update.

It appears that Segment is working as intended. Here's what might be leading to inconsistent behavior:

### Cookies
In order for page load and click event tracking to work, a user **must** have at least `Functional cookies` enabled. Please read this thread from our internal [#bmx-segment-commonlib](https://ibm-quantumcomputing.slack.com/archives/C37AQP8F2/p1654706215441229) channel.

> Hey Randy, we will only load Segment if the user has allowed `Functional` cookies.

> ... We recognize personalized/advertising as a higher level of consent than functional, so we load functional services if `Personalized` is allowed.

### Screen capture (evidence)

https://user-images.githubusercontent.com/6276074/172679384-2ec6186b-1a8b-4c4b-afc9-2a784d9fc60f.mov

You'll see in the screen capture above:
- with the 'Required' (minimal) cookies, Segment does not track
- I reload the page to show nothing is tracking
- however, when I slide the cookies settings to `Functional`, then Segment begins tracking
- and as I navigate into our Syllabus page, Segment continues to track click events and page loads


Let me know what your thoughts are here; otherwise, I don't think there's a bug in our code.

**Comment by techtolentino** [comment] 2022-06-10 00:30
Closing this issue because our Segment analytics is working as expected. 

This, then, becomes sort of a UX challenge, in the sense that we could figure out a way to nudge users into accepting at least, the `Functional cookie` level.

**Closed by techtolentino** 2022-06-10 00:30 UTC
Labels: bug, size: S, analytics
