### ISSUE TITLE
Typesetting on Deutsch-Jozsa Algorithm page

### ISSUE THREAD

**Issue by jhwatrous** [Qiskit/platypus#1012] opened 2022-05-16 20:33 UTC
### Steps to reproduce the problem

1. Go to https://learn.qiskit.org/course/ch-algorithms/deutsch-jozsa-algorithm
2. Scroll down to 'Worked Example' section (for example)

### What is the current behavior?

There are multiple typesetting errors, including equations that are too long and an inline equation that does not render correctly.

### What is the expected behavior?

Equations should fit on the page and render correctly.

### Screenshots (optional but very helpful)

<img width="1212" alt="Screen Shot 2022-05-16 at 4 30 37 PM" src="https://user-images.githubusercontent.com/100238302/168677406-201af96d-5a33-408c-9dc7-77afabc6a6dd.png">

### Environment (optional but very helpful)
 - Device: iMac Pro
 - OS: Mac OS 
 - Browser: Chrome

**Comment by micpap25** [comment] 2023-01-24 02:13
Duplicate of #518 and #387

**Comment by vabarbosa** [comment] 2024-02-08 04:58
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).

**Closed by vabarbosa** 2024-02-08 04:58 UTC
Labels: ARCHIVED
