### ISSUE TITLE
[Content UI] Long math equations can't be seen completely

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/platypus#387] opened 2021-12-02 16:24 UTC
### Steps to reproduce the problem

1. Go to https://learn.qiskit.org/course/quantum-hardware-pulses/circuit-quantum-electrodynamics#tcreg on a device with a small viewport (like a tablet)
2. Scroll down to the section "5. Qubit Drive with cQED"
3. See the long equations

### What is the current behavior?

Long equations don't fit on the viewport and cannot be read completely.

### What is the expected behavior?

Long equations should be accessible in small viewports.

Ideas for possible solutions:
1. Breaking them in multiple lines
2. Make them horizontally scrollable

### Screenshots (optional but very helpful)

![Screenshot 2021-12-02 at 17 23 38](https://user-images.githubusercontent.com/22047320/144461773-cb7b88f6-d14b-45d5-ba86-d221fda95313.png)

### Environment (optional but very helpful)
 - Device: iPad (Simulated in Chrome)
 - OS: MacOS
 - Browser: Chrome

**Comment by eddybrando** [comment] 2022-02-10 16:25
Also happening on https://learn.qiskit.org/course/machine-learning/unsupervised-learning with a small viewport device:

Simulated Pixel 5:

![Screenshot 2022-02-10 at 17 25 15](https://user-images.githubusercontent.com/22047320/153451283-81e9f9e9-5bbb-439e-bf7c-726158b98656.png)

**Comment by micpap25** [comment] 2023-01-24 02:12
Duplicate of #518

**Comment by vabarbosa** [comment] 2024-02-08 04:49
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).

**Closed by vabarbosa** 2024-02-08 04:49 UTC
Labels: bug, ARCHIVED
