### ISSUE TITLE
[Content UX] Math equations can't be copy/pasted

### ISSUE THREAD

**Issue by JRussellHuffman** [Qiskit/platypus#468] opened 2021-08-13 17:48 UTC
Math equations can't be copy/pasted in the new textbook, but could be copy/pasted in the old textbook (see screenshots below). We should re-introduce this feature before officially replacing the old version of the textbook.

Old textbook:
<img width="284" alt="Screen Shot 2021-08-13 at 12 46 33 PM" src="https://user-images.githubusercontent.com/7633881/129399221-3096f659-e7ec-4243-9169-19e129eaf8b0.png">

New textbook:
<img width="329" alt="Screen Shot 2021-08-13 at 12 46 45 PM" src="https://user-images.githubusercontent.com/7633881/129399249-1aee37b4-c9be-40c9-8782-c096995cff6b.png">

**Comment by eddybrando** [comment] 2022-05-20 08:13
Duplicate of #428

**Closed by eddybrando** 2022-05-20 08:13 UTC
Labels: duplicate
