### ISSUE TITLE
[Content UI] Math text too long on frqi page

### ISSUE THREAD

**Issue by JRussellHuffman** [Qiskit/platypus#350] opened 2022-01-27 16:14 UTC
### Steps to reproduce the problem

1. Go to https://learn.qiskit.org/course/ch-applications/flexible-representation-of-quantum-images-frqi
3. Scroll down to https://learn.qiskit.org/course/ch-applications/flexible-representation-of-quantum-images-frqi#flexible-29-0
4. See math equation that is too long

### What is the current behavior?

Math goes beyond container

### What is the expected behavior?

Math equation should fit the container

### Screenshots (optional but very helpful)
<img width="979" alt="Screen Shot 2022-01-27 at 10 11 45 AM" src="https://user-images.githubusercontent.com/7633881/151397986-98ca4e4e-3903-4823-8d49-7f2f84b01f86.png">

**Comment by eddybrando** [comment] 2022-05-20 08:04
Duplicate of https://github.com/Qiskit/platypus/issues/466

**Closed by eddybrando** 2022-05-20 08:04 UTC
Labels: duplicate
