### ISSUE TITLE
Vector diagram showing computational basis |+> and |-> is wrong

### ISSUE THREAD

**Issue by priyabratabiswas** [Qiskit/platypus#1790] opened 2023-01-04 15:47 UTC
In the qiskit textbook new beta verion in this page --
https://learn.qiskit.org/course/introduction/describing-quantum-computers
Vector diagram showing computational basis |+> and |-> is wrong. |0> and |1> should be reversed as I have shown in the attached screen shot.

Priyabrata Biswas, Ph.D
IBM,
priyabrata.biswas@ibm.com

<img width="956" alt="basis" src="https://user-images.githubusercontent.com/18732485/210593845-2acf414a-22f4-4657-8651-8be84fd7ab9f.png">

**Comment by frankharkins** [comment] 2023-01-10 10:03
Thanks! This is a duplicate of #900, but I think this solution is better as we define
```math
|0\rangle = \begin{bmatrix} 1 \\ 0 \end{bmatrix}
```
and conventionally the x-axis is the first element of a vector.

**Closed** 2023-01-18 06:07 UTC

**Comment by priyabratabiswas** [comment] 2023-01-19 13:58
Thank you @frankharkins
